name: Release messages to discord announcement channel

on: 
  release:
    types: [published]

jobs:
  run_main:
    runs-on: ubuntu-latest
    name: Sends release details to discord
    steps:
      - name: Sending message
        uses: nhevia/discord-styled-releases@main
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
